menu:
  Archives: /archives
  Travel: /tags/行
  Reading: /tags/读
  About: /about
rss: /atom.xml

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: onetracy

google_analytics:
favicon: /favicon.ico
